### ISSUE TITLE
Unable to install through composer

### ISSUE THREAD

**Issue by robjbrain** [more-cores/laravel-restcord#14]
There seems to be an issue with how this is registered with composer:

`composer require more-cores/laravel-restcord:dev-master`

> ./composer.json has been updated
> Loading composer repositories with package information
> Updating dependencies (including require-dev)
> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - The requested package more-cores/laravel-restcord could not be found in any version, there may be a typo in the package name.
> 
> Potential causes:
>  - A typo in the package name
>  - The package is not available in a stable-enough version according to your minimum-stability setting
>    see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
> 
> Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
> 
> Installation failed, reverting ./composer.json to its original content.

**Comment by bkuhl** [comment]
Doh!  I had renamed the repo initially after setting up packagist which appeared to have broken this.  You're all set now.   Release v1 should be coming up soon, this is working well for me so far.
