### ISSUE TITLE
Unable to install with Laravel 5.6

### ISSUE THREAD

**Issue by keesh7663** [more-cores/laravel-restcord#27]
`restcord/restcord dev-master requires symfony/options-resolver >=2.6,<=4.0`

However in 5.6, it upgrades to symfony/options-resolver:4.0.4

**Comment by keesh7663** [comment]
I submitted a new issue on restcord/restcord#44 and they were able to start work on bumping the symfony versions to accommodate Laravel 5.6.  Closing this as all that needs to be done now is wait for a master merge.

**Comment by bkuhl** [comment]
Great, thanks!

**Comment by aequasi** [comment]
Has been merged
